Merged revision(s) 7055-7079 from trunk: 2. apply suggested Patch from Mark according Ticket #457 Thank's for reporting! ........ add missing GetGUID to IZPreparedStatement ........ OleDB gurantiee the Serverprovider is determined ........ add missing stBytes length determination ........ optimized Array to Typed conversion ........ For the DOC's SQLite add GUID field determination ........ proper start of stream on reading the lobs ........ add testcase for Ticket #458, bug is not reproduceable on v8 ........ enable GetCLob method (distinct vs. IZBLOB) for later purpose ........ preview of my promisse to make Batch DML bindings possible on component-layer. Just save code. Not yet used! ........ using the TEST_TZPARAM define ........ Test case for SF#460 ........ @Egonhugeist: please check this patch. proposed patch from aehimself. See https://zeoslib.sourceforge.io/viewtopic.php?f=37&t=129194&p=159629#p159629 ........ try to handle aehimself reported datasize issue, and Mark's notes according the ftWideMemos for varchar() outparams ........ Reverting changes from r7070 / aeafa71. They create some test errors: Exception: [EZSQLException] SQL Error: OCI_INVALID_HANDLE Code: -2 Message: OCIDescriptorFree
Exception: [EAccessViolation] Access violation at address 61F39BB3 in module 'OraClient11.Dll'. Read of address 00F338BC
at: $61F39BB3
........
try handle aehimself's report about lob-close performance penalty by ising a own Variable and bypass OCILobIsOpen
........
commit second WC-copy of ZDatasetParam.pas
........
PG partial fix to detect $-taget parameter tokens (not body tags!)
........
Patch my MJFShark: Correct behavior of TZTimeField and TZDateTimeField to show fractions of seconds if the field is declared with these.
See https://zeoslib.sourceforge.io/viewtopic.php?f=25&t=129208 and https://zeoslib.sourceforge.io/viewtopic.php?f=50&t=129204
........