Merged revision(s) 4925-5028 from branches/testing-7.3: 7.2: - move TestArrays to the protected section so it isn't used as a test anymore. - correct some errors in TZTestDbcPostgreSQLCase.TestEnumValues -> update and delete statements don't give result sets anymore ........ 7.2: disabled TZTestDbcOracleCase.TestStatement because this just doesn't make sense ........ 7.2: disabled test Test924861 because I am not sure wether this is intended behaviour. See SF#292 ........ 7.2: - ZDbcDbLibMetadata.pas: make TZDbLibDatabaseInfo.StoresMixedCaseIdentifiers aware of icMixed. This solves a bug in the test Mantis164 on case sensitive databases - ZDbcDbLibResultSet.pas: fix a comparison so that columns get readonly if they are meant to be readonly. Although I highly doubt that this fixes anything for anybody ........ 7.2: change the magic numbers in MysqlTypeToZeos to Ord(ZSqlType) constructs. This fixes a bug in Zeos 7.2 where ZSqlTypes have a different order. ........ 7.2: - enable the FPC ZTestAll to use the xml parameter that Delphi ZTestAll uses - enable the FPC ZTestAll to set a custom test suite name via the suitename parameter, at least two test suites must be selected via the suite paramater - enhance the GetCommandLineSwitch function for Delphi to be able to work with case insensitive parameters - enhance the GetCommandLIneSwitch function for Delphi to be able to use GNU style long parameters (--<parametername>[=<parametervalue>]) - add a proxy FindCmdLineSwitch in ZTestConfig.pas to enable the use of GNU style long parameters (--<parametername>[=<parametervalue>]) with the Delphi test suite ........ *7.2* Test suite: fix "Ambiguous overload" error on D7 with UInt64 parameters ........ *7.2* Test suite: changed test exception class because EAbstractError was declared platform on D7 ........ *7.2* Many pointer=>uint typecasts changed to safe PByte typecasts ........ *7.2* Test suite: small changes ........ *7.2* Test suite: added WITH_OVERLOAD_BUG define for D7 (for its inability to expand values of smaller int types to larger ones correctly) which is used to add Check(Not)Equals overloads to fix "Ambiguous overload" error.
........
FB/IB: utilities cleanup.
- Two generic DB info routines (GetDBIntegerInfo and GetDBStringInfo) based on GetISC_StringInfo and GetFB_ISC_IntegerInfo; GetDBImplementationNo and GetDBImplementationClass removed (not used); GetLongDbInfo and GetStringDbInfo removed (they were doing the same).
- isc_portable_integer which returns int64 replaced with isc_vax_integer which returns int32.
- Added two ConvertConnRawToString overloads that allow shorter reading of DB raw text
- all routines that acquire info from server are standardized in buffer names, function calls etc.
........
FB/IB: identical pieces of code extracted to ConvertConnRawToStringWithOpt routine
........
Typecast to make D7 happy
........
*7.2* FB/IB: Fixed re-enabling of range checking: it doesn't depend on Debug switch at all.
........
*7.2* Compiler options-related defines cleanup:
- Added global OverFlowCheckEnabled define to generic include file
- All local compiler options-related defines removed in favor of generic RangeCheckEnabled and OverFlowCheckEnabled
........
*7.2* Compiler options-related defines cleanup for lists and collection:
- Checks are enabled by DISABLE_CHECKING define instead of RangeCheck (that is what DISABLE_CHECKING is intended for)
- internal ReturnAddr functions replaced with intrinsic ReturnAddress (available since XE2); older versions use ZCompatibility.ReturnAddress which was made available for non-asm compilation too.
........
*7.2* Added StreamFromData functions to shorten stream creation.
........
*7.2* Finally resolved internal error C1118 bug on D7 without complete disabling of range check.
........
7.2: Fix for the new proxy FindCmdLineSwitch function - it called the sysutils function but never used the result..
........
Minor optimization
........
*7.2* IFNDEF UNIX => IFDEF MSWINDOWS which is more correct (MacOS, Linux, Android etc are not Unix)
........
*7.2* Removed usage of OLD_FPC define, cleanup of uses section
........
*7.2* (Lazarus) test suite project optimizations:
- uses section cleanup
- predefined Run parameters removed
- path to fpcunit removed from SearchPath. It was useless and made compiler rebuild all fpcunit units every time the project was rebuilt.
- all available check and debug options enabled
........
*7.2* Started activity on removing globally disabled warnings and hints. Idea is to disable only specific hints and as minimally as possible. Thus compiler will help finding bugs.
........
*7.2* TZAbstractRODataset.GetActiveBuffer, TZAbstractPreparedStatement2.Get*, IZConnection.Get(Binary)EscapeString - result parameter declared as "out" instead of "var" (this eliminated many "variable not init'd" warnings)

........
*7.2* More hints/warnings stuff - now for drivers. Currently compiler will print messages regarding deprecated constructors.
........
*7.2* More warnings stuff. This helped to fix usage of deprecated Thread.Resume and forgotten result assignment in TZQuoteState.DecodeString
........
*7.2* Defines cleanup: HAVE_TBYTES, WITH_EARGUMENTEXCEPTION, MISS_VARIANTCLEAR replaced with IF DECLARED; WITH_FPC_STRING_CONVERSATION => WITH_FPC_STRING_CONVERSION; unused MULTI_THREADED, USELIBFBCLIENTSO, USE_SYNEDIT commented out and marked with TODO
........
*7.2* BytesOf seems not used by any unit ?? Removed for now; anyway one could use ZSysUtils.BufferToBytes instead
........
*7.2* Cosmetic change: removed ifdefs inside ADO and OleDB units. If these drivers are disabled, they shouldn't be used at all so ifdefs inside are excessive.
........
*7.2* Remove warnings disabling for drivers pt.2
........
*7.2* More hints enabling. Disabled WARN 4056 as well. more "var" parameters declared as "out"
........
*7.2* more "var" parameters declared as "out"
........
*7.2* (FPC) Warnings hunt. Added definition of WITH_ASANSISTRING and new define WITH_ASUTF8STRING (3.0.2+)
........
*7.2* more "var" parameters declared as "out"
........
7.2: moved the check for EArgumentException. Placing it right behind the uses clause triggers "Internal error 200501152" on FPC 2.6
........
7.2: Add some ifdefs that reenable using infinity an neginfinity on FPC 2.6 with range checks enabled. Just using them without ifdefs will throw an compiler error: "Range check error while evaluating constants". Strange.
........
*7.2* More warnings hunt. FPC warnings are disabled on minimal possible areas with PUSH/POP technique (thus respecting project-defined options)
........
*7.2* Removed per-unit warning switching as they're disabled globally
........
*7.2* Re-enabled ZTestCompADOBugReport for FPC. What was the reason for its disabling?
........
7.2: pushing the use of {$DEFINE WITH_ASANSISTRING} and {$DEFINE WITH_ASUTF8STRING} to any FPC version after 3.0.4. Using them with FPC 3.0.4 breaks the build.
........
Added a new xml output module for the test suite. I hope this works better with Hudson and Jenkins...
........

........

........
*7.2* ZDbcCache, redesigned comparison routines - they use matrices for comparison of null flags  (faster and less code). Fixed bug with these flags not being used for blobs
........
*7.2* Added ZTest.inc to store defines that influence all test suite units (but not Zeos source units), for example, to suppress any warnings and hints in test units.
........
*7.2* more "var" parameters declared as "out"
........
*7.2* FB/IB: date/time routines use named constants, disable WARN 4081
........
*7.2* Almost all remaining places where warnings has been switched globally removed.
........
*7.2* Removed warnings on hidden methods with the help of "reintroduce"
........
*7.2* Simplified code of TZAbstractRODataset.CreateFields. WITH_IPROVIDERSUPPORT_NG define replaced with IF DECLARED clause
........
OleDB infinate loop on unprepare
........
7.2* theoretical memleak on FPC with the symbol states
........
7.2* revert theoretical memleak on FPC with the symbol states
........
7.2? These changes fix some problems with the SAP ASE univarchar type
........
*7.2* use temp variable to shorten the code - I just couldn't leave these loooong lines :)
........
these changes should make the xml output for FPC more NUnit 3.0 compatible.
........

........
*7.2* more "var" parameters declared as "out"
........
*7.2* TZRowAccessor.AllocBuffer - removed parameter as it was useless. TZRowAccessor.Alloc now is a procedure forcing caller to use property that it allocated. Previous version was hiding the fact it was changing something internally. Inspired by hints FPC produced.
........
*7.2* minor change and fix a hint
........
*7.2* Define WITH_TRECORDBUFFER and many lines of conditional code replaced by declaring TRecordBuffer if not declared. The same with TGetCalcFieldsParamType which represents a type that GetCalcFields expects.
........
*7.2* Enabled a hint and fixed bug for FPC - TField has FieldDef property which was used instead of method parameter.
........
*7.2* Minor - remove hints disabling (most of them are not actual because of var=>out change, others will be reviewed later)
........

........
*7.2* Removed usage of ComObj for FPC@Win32 in generic units - seems excess.
........
*7.2* Delphi defines cleanup: WITH_SYSTEM_WIN_COMOBJ, WITH_VCL_PREFIX and WITH_SYSTEM_PREFIX merged into WITH_UNIT_NAMESPACES; WITH_SYSTEMCLASSES, WITH_IPROVIDERSUPPORT2, WIDE_DATASET, WITH_REPORTMEMORYLEAKSONSHUTDOWN, WITH_TENCODING_CLASS, NO_POINTER_InternalAddRecord, WITH_NATIVEINT_ClearCalcFields removed as unused
........
*7.2* more "var" parameters declared as "out" and more FPC hint disabling removed
........
*7.2* TZAbstractConnection.SetVersion removed (was empty and unused)
........
Fix mistake that disabled INSERT..RETURNING support
........
*7.2* more hint disabling removed. Fixed not returning IsNull in TZRowAccessor.GetDataSet
........
*7.2* Test suite: code in TZGenericTestDbcResultSet.TestStringGetter squeezed to loop and added string typecasts to eliminate warnings
........
*7.2* Test suite: FPC's CheckException turned out to not allow ancestors of expected exception class. Checks and Delphi version corrected appropriately. This fixed 2 failing tests on FPC
........
*7.2* Suppress some FPC hints that are known to be false. P.S. Revision 5000! =)
........
*7.2* Test suite: fix of r.4998 that prevented build on D7
........
*7.2* Fixed bug with keyword couldn't be found on FPC that made TestMetadataIdentifierQuoting fail. Keywords storage in TZAbstractDatabaseInfo changed from array of string to TStringList. This significantly reduced and simplified code (Michael I awfully apologize it was yours but it was really a black magic).
........
7.2* possible FPC MemLeak 4 bind arrays bindings
........
MySQL small changes to prevent rebindings
........
7.2* MySQL cant call mysql_affected_rows if FieldCount > 0
........
new GUID buffer writer with options
........
Oracle new fast stmt -> yet out of use
........
7.2* Oracle if RangeChecks are anabled StoredProcs failed
........
brocken copmpilation on last oracle commit

........
missing oracle const
........
mysql exception on rawtointdef
........
7.2: Make the output of the xml test runner more compliant to NUnit 3 - hope it is enough for Jenkins
........
7.2: Fixing a small error in the delphi xml output unit
........
7.2: add the type attribute to the test suite tags on creation
........
7.2: Correct the TXMLNode to IXMLNode - again!
........
7.2: Add some more properties to the Delphi xml output and make the class name attribute behave the same as on FPC.
........
7.2: reorder and add some attributes to the test cases so they con be compared to FPC more easily. Some of the attributes are dummys though...
........
7.2: some more corrections
........
*7.2* Minor internal changes
........
*7.2* fix constant declarations - incorrect LineEnding for Delphi & not-Windows
........
*7.2* Duplicated code in TZ(Single|Double|Currency|Extended)Fields united in base class
........
*7.2* Internal ZSysUtils improvements
........
*7.2* TZAbstractDriver, caches plain drivers with case-insensitive protocols and lib paths. Tests added
........
*7.2 partially* IZDriverManager:
- robust thread-safety (internal CS'es to access fields)
- removed field FURL, methods use newly created object
- removed LoginTimeout (unused)
- removed ResolveDatabaseUrl, ZDbcUtils.ResolveDatabaseUrl as unused.
........
- *7.2* Test suite: GetConnectionUrl moved to TZAbstractSQLTestCase and returns TZURL
 7.2* oci type corrections
- Oracle enable new Fast PreparedStatements with direct bindings
- resolve ODBC hint